modLoader="javafml" 
loaderVersion="[43,)" 
license="MIT License"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="dungeons_mobs"
version="${file.jarVersion}" 
displayName="Dungeons Mobs" 
# updateJSONURL="http://myurl.me/" 
# displayURL="http://example.com/"
logoFile="examplemod.png" 
credits="Infamous Mods" 
authors="the_infamous_1" # TODO maybe replace it with the dev names here(?)
description='''
'''

[[dependencies.dungeons_mobs]] 
    modId="forge"
    mandatory=true 
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.1.38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="dungeons_libraries" 
    mandatory=true 
    versionRange="[1.19.2-3.0.10-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="enchantwithmob" 
    mandatory=false 
    versionRange="[1.19.2-7.0.1,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="jei" 
    mandatory=false 
    versionRange="[11.2.0.247,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="justenoughresources" 
    mandatory=false 
    versionRange="[1.2.1.189,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="jeed" 
    mandatory=false 
    versionRange="[1.18,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="roughlyenoughitems" 
    mandatory=false 
    versionRange="[9.1.580,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="roughlyenoughresources" 
    mandatory=false 
    versionRange="[2.5.2,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="architectury" 
    mandatory=false 
    versionRange="[6.4.62,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="clothconfig" 
    mandatory=false 
    versionRange="[8.2.88,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.dungeons_mobs]] 
    modId="configured" 
    mandatory=false 
    versionRange="[2.0.1,)" 
    ordering="NONE"
    side="CLIENT"

[[dependencies.dungeons_mobs]] 
    modId="catalogue" 
    mandatory=false 
    versionRange="[1.7.0,)" 
    ordering="NONE"
    side="CLIENT"

[[dependencies.dungeons_mobs]] 
    modId="appleskin" 
    mandatory=false 
    versionRange="[2.4.2,)" 
    ordering="NONE"
    side="CLIENT"